### ISSUE TITLE
Load multiple marker files at once

### ISSUE THREAD

**Issue by SchoolGuy** [AsherGlick/Burrito#123] opened 2023-02-19 20:44 UTC
As a user of Burrito
I want to load multiple marker files at once
so that I don't have to manually switch between them all the time.

**Comment by AsherGlick** [comment] 2023-02-19 21:49
This is a part of the XMl loader project #64, notes for it can be found in #75 and in the PR #114 . I am going to close this as a duplicate only because #114 already has code to do this so there is no chance this feature wont be included in the overall project, even though it is not actually a duplicate of anything.

**Closed by AsherGlick** 2023-02-19 21:49 UTC
