### ISSUE TITLE
Burrito icon overlaping tradingpost

### ISSUE THREAD

**Issue by Masgalor** [AsherGlick/Burrito#219] opened 2023-11-13 09:24 UTC
I've installed the latest release available here on Github (Alpha 1.4) and noticed that the burrito icon overlaps the tradingpost icon.
This confuses me because there is already a merged PR to fix this https://github.com/AsherGlick/Burrito/pull/156 .
I'm not sure what to do now, do I need to build burrito myself from master to get this fix?

**Comment by AsherGlick** [comment] 2023-11-13 14:13
This issue should be in the most recent stable release, that release was cut specifically for the issue. If there is a bug and it is not working for some reason then we will try to address it.

Can you attach:
* A screenshot of this issue with no menus open (and no red outline around burrito)
* A screenshot of this issue with at least one menu open (with a red outline around burrito)
* What in-game UI scale you play on
* How you are launching burrito link (d3d11.dll / standalone executable / something else)
* The output to the commands `inxi -Gxxx`  and `wmctrl -m` (just in case)

**Comment by Masgalor** [comment] 2023-11-13 17:45
I'm launching the burrito-link standalone executable with a script generated bey lutris as explained in the instructions.
Maybe it's worth mentioning, that everything else (e.g. range indicator or markers) is where it is supposed to be.

 - Interface size: big
 - DPI-Scaling: disabled

![1](https://github.com/AsherGlick/Burrito/assets/30129213/1f5b6bde-2aab-4dd3-9e13-1ec8156bebf4)
![2](https://github.com/AsherGlick/Burrito/assets/30129213/87654aa4-9261-4cc6-b47e-e85e413ea032)

```
user@localhost:~> inxi -Gxxx
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    vendor: Sapphire driver: amdgpu v: kernel arch: RDNA-1 pcie: speed: 16 GT/s
    lanes: 16 ports: active: DP-2,DP-3 empty: DP-1,HDMI-A-1 bus-ID: 0b:00.0
    chip-ID: 1002:731f class-ID: 0300
  Display: x11 server: X.Org v: 21.1.9 with: Xwayland v: 23.2.2
    compositor: kwin_x11 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 5120x1440 s-dpi: 96 s-size: 1354x381mm (53.31x15.00")
    s-diag: 1407mm (55.38")
  Monitor-1: DP-2 mapped: DisplayPort-1 pos: primary,right model: VG27B
    serial: L6LMQS029772 res: 2560x1440 dpi: 109 size: 597x336mm (23.5x13.23")
    diag: 685mm (27") modes: max: 2560x1440 min: 720x400
  Monitor-2: DP-3 mapped: DisplayPort-2 pos: left model: VG27B
    serial: M4LMQS275540 res: 2560x1440 dpi: 109 size: 597x336mm (23.5x13.23")
    diag: 685mm (27") modes: max: 2560x1440 min: 720x400
  API: OpenGL v: 4.6 Mesa 23.2.1 renderer: AMD Radeon RX 5700 XT (navi10
    LLVM 17.0.3 DRM 3.54 6.5.9-1-default) direct-render: Yes
```

```
user@localhost:~> wmctrl -m
Name: KWin
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

**Comment by AsherGlick** [comment] 2023-11-13 18:19
From this info there is a 99% chance it is `Interface size: big` . Values other then normal is something we have not implemented yet, though it is entirely possible to do so and we plan to do this eventually.

If you are feeling ambitious you can hack this for yourself. All you will need to do is reexport the overlay executable itself after making an edit, you can reuse the other libraries you already downloaded without rebuilding them. I think you will need to adjust [this line](https://github.com/AsherGlick/Burrito/blob/a344bdfcfa738ca764ffe677c5f7ba10217b15db/Spatial.tscn#L74) but I am not 100% sure about that. [Here are the instructions](https://github.com/AsherGlick/Burrito/blob/237117f58763a60b9c30ca2356a600adbcd579da/.github/workflows/main.yml#L151-L209) to export it yourself entirely through the command line. You can also just download godot 3.3.2 and export it manually, all the export settings are preconfigured and there are instructions online for how to export godot projects in general.

Our priority right now is trying to finish #64 by the end of the year, so dont expect much from us  in way of prioritizing this before then. That said, I will happily review a pr for dynamic ui-size adjustments from you or anyone else. The value that will need to be read is `uisz` inside the json `identity` field from the [mumble api](https://wiki.guildwars2.com/wiki/API:MumbleLink). iirc we are actually already sending that data over via mumble link, but I dont know what all will need to be adjusted based on that setting.

**Comment by AsherGlick** [comment] 2023-11-13 19:47
I am going to close this as a duplicate of #16 . If this is not actually the issue feel free to re-open it. If you have any quick questions about this manual fix I can try to help but I wont be able to walk you through it more then the guidance above, someone else might though.

**Closed by AsherGlick** 2023-11-13 19:47 UTC
Labels: bug, user interface

**Comment by Masgalor** [comment] 2023-11-14 11:15
You are absolutely right, the problem here is that the burrito icon doesn't adjust itself to the interface scale.
I really appreciate your detailed answer to this issue, I had no problems to write a patch that places the icon dynamically depending on the interface scale.

I will ope a draft PR to see if you think it's usable.
